name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make
      - name: Set up Qt
        run: |
          sudo apt-get update    
          sudo apt-get install -y qt5-default
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

  # You can add additional jobs here, 
  # for example, a job to run unit tests.
