name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make qtbase5-dev qtdeclarative5-dev qt5-qmake qttools5-dev-tools

      - name: Set up Qt environment
        run: |
          echo 'QT_DIR=$(qtchooser -print-env | grep QTTOOLDIR | cut -d= -f2)/..'
          echo 'export PATH=$QT_DIR/bin:$PATH' >> $GITHUB_ENV
          echo 'export CMAKE_PREFIX_PATH=$QT_DIR' >> $GITHUB_ENV

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make qtbase5-dev qtdeclarative5-dev qt5-qmake qttools5-dev-tools

      - name: Set up Qt environment
        run: |
          echo 'QT_DIR=$(qtchooser -print-env | grep QTTOOLDIR | cut -d= -f2)/..'
          echo 'export PATH=$QT_DIR/bin:$PATH' >> $GITHUB_ENV
          echo 'export CMAKE_PREFIX_PATH=$QT_DIR' >> $GITHUB_ENV

      - name: Run tests
        run: |
          cd build
          make test

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VALIDATE_ALL_CODEBASE: true
  VALIDATE_JAVASCRIPT_ES: true
  VALIDATE_PYTHON_PYLINT: true
  VALIDATE_GO: true
  VALIDATE_CPP: true
  DEFAULT_BRANCH: main
