name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make
      - name: Set up Qt 
        run: |
         sudo apt-get update
         sudo apt-get install -y qtbase5-dev qtdeclarative5-dev qt5-qmake qttools5-dev-tools
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

          env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          VALIDATE_ALL_CODEBASE: true 
          VALIDATE_JAVASCRIPT_ES: true 
          VALIDATE_PYTHON_PYLINT: true 
          VALIDATE_GO: true VALIDATE_CPP: true 
          DEFAULT_BRANCH: main

  # You can add additional jobs here, 
  # for example, a job to run unit tests.
