name: Build, Run, and Deploy C++ Code

# Trigger the workflow on push or pull request to the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # Check out the master branch
        ref: master

    - name: Set up environment
      run: sudo apt-get install -y g++

    - name: Build the code
      run: g++ -o tictactoe in.cpp

    - name: Run the code
      run: ./tictactoe
      # If your code requires inputs, you can use echo and pipe the inputs to the executable.
      # For example: echo "1\n2\n3" | ./tictactoe

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        echo "<html><body><pre>$(./tictactoe)</pre></body></html>" > index.html
        git add index.html
        git commit -m 'Deploy to GitHub Pages'
        git push origin HEAD:gh-pages
