name: Build, Run, and Deploy C++ Codee

# Trigger the workflow on push or pull request to the master branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-run-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
     
